version: '3.8'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:1.18-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 443:443
            - 5173:5173
        volumes:
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl/webte_fei_stuba_sk.pem:/etc/nginx/certs/webte_fei_stuba_sk.pem
            - ./nginx/ssl/webte.fei.stuba.sk.key:/etc/nginx/private/webte.fei.stuba.sk.key
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}'
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
        ports:
            - '${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}'
        networks:
            - laravel
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:5
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - laravel
        ports:
            - 8001:80
